version: '3'

services:
  distcc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CROSS_TARGETS: |
          armv7a-unknown-linux-gnueabihf
          aarch64-unknown-linux-gnu
          powerpc-unknown-linux-gnu
    ports:
      - "3632:3632"
    volumes:
      - distcc-ccache:/var/cache/ccache

volumes:
  distcc-ccache:
