version: '3'

services:
  gentoo-cross-compile:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BINUTILS_VER: "2.34" # Replace with the actual version
        GCC_VER: "9.3.0"     # Replace with the actual version
        KERNEL_VER: "5.4"    # Replace with the actual version
        LIBC_VER: "2.31"     # Replace with the actual version
    environment:
      DISTCCD_JOBS: 4
      DISTCCD_ALLOW: "192.168.1.100" # Replace with your IP or range
      DISTCCD_LOG_LEVEL: info
      DISTCCD_LOG_FILE: /var/log/distcc.log
    volumes:
      - ./src:/src
    ports:
      - "3632:3632"
    networks:
      - crossnet

networks:
  crossnet:
