version: '3'

services:
  gentoo-cross-compile:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: "gentoo/stage3:amd64-nomultilib-openrc" # Use nomultilib profile
        STABLE_BUILD: "yes"  # Use "yes" for stable, "no" for finetuned binutils,gcc,kernel,libc
        BINUTILS_VER: "2.41" # Replace with the actual version if unstable
        GCC_VER: "11.4.1"     # Replace with the actual version
        KERNEL_VER: "6.6.13"    # Replace with the actual version
        LIBC_VER: "2.38"     # Replace with the actual version
        CROSSDEV_TARGETS: "aarch64-unknown-linux-gnu arm-unknown-linux-gnueabi powerpc-unknown-linux-gnu i686-pc-linux-gnu" # Multi-arch targets: arm64 arm ppc32 x86
        # Available arches: amd64 alpha arm arm64 hppa loong mips m68k ppc riscv s390 sparc x86
    environment:
      DISTCCD_JOBS: 4
      DISTCCD_ALLOW: "192.168.1.0/0" # Replace with your IP or range
      DISTCCD_LOG_LEVEL: info
      DISTCCD_LOG_FILE: /home/crossdevuser/distcc.log
    volumes:
      - ./src:/src
    ports:
      - "3632:3632"
    networks:
      - crossnet

networks:
  crossnet:
